# Generated by Django 4.2.14 on 2024-07-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_image_alter_product_image_cartitem'),
        ('shop', '0003_alter_category_image_alter_product_image'),
    ]

    operations = [
    ]
