version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose le port 8000 du conteneur sur le port 8080 de l'hôte

    volumes:
      - .:/app   # Montez le répertoire courant dans /app du conteneur
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce.settings
    command: >
      sh -c "python manage.py test shop.tests_shop && python manage.py runserver 0.0.0.0:8080"


