name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      - name: Run tests
        run: docker-compose -f docker-compose.yml run web python manage.py test shop.tests_shop

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t isa95330/ecom-name:latest -f Dockerfile .

      - name: Push Docker image
        run: docker push isa95330/ecom-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ec2-user@ec2-15-237-160-93.eu-west-3.compute.amazonaws.com << 'EOF'
          docker pull isa95330/ecom-name:latest
          docker-compose -f /home/ec2-user/src/docker-compose.yml down
          docker-compose -f /home/ec2-user/src/docker-compose.yml up -d
          EOF
